const data = [
  "(me narrating a documentary about narrators)I can't hear what they're saying cuz I'm talking",
  "I want to die peacefully in my sleep like my grandfather did. Not screaming in terror like the passengers in his car.",
  "They all laughed when I said I wanted to be a comedian. Well, they're not laughing now!",
  "I told my physical therapist that I broke my arm in two places. He told me to stop going to those places.",
  "How do you make holy water? You boil the hell out of it.",
  "I was wondering why the ball was getting bigger. Then it hit me.",
  "Telling my daughter garlic is good for you. Good immune system and keeps pests away.Ticks, mosquitos...",
  "I've been going through a really rough period at work this week It's my own fault for swapping my ta...",
  "If I could have dinner with anyone, dead or alive... ...I would choose alive. -B.J. Novak-",
  "Two guys walk into a bar. The third guy ducks.",
  "Why can't Barbie get pregnant? Because Ken comes in a different box. Heyooooooo",
  "Why was the musician arrested? He got in treble.",
  "Did you hear about the guy who blew his entire lottery winnings on a limousine? He had nothing left ...",
  "What do you do if a bird shits on your car? Don't ask her out again.",
  "He was a real gentlemen and always opened the fridge door for me",
  "(Telling my daugthers date that )she has lice and its very contagious the closer you get to her. *Co...",
  "What should you do before criticizing Pac-Man? WAKA WAKA WAKA mile in his shoes",
  "What's the difference between an illegal Mexican and an autonomous robot...? Nothing... they were bo...",
  "What do you call a barbarian you can't see? an Invisigoth.",
  "How do you spell Canda? C,eh,N,eh,D,eh",
  "You ever notice that the most dangerous thing about marijuana is getting caught with it?",
  "What did Arnold Schwarzenegger say at the abortion clinic? Hasta last vista, baby.",
  "My wife is in a bad mood. I think her boyfriend forgot their anniversary. Way to go, dude. Now we al...",
  "My speech today will be like a mini-skirt. Long enough to cover the essentials but short enough to h...",
  "Thanksgiving joke What does Miley Cyrus eat for Thanksgiving? Twerky! Just kidding... Drugs. She eat...",
  "Why do you never see elephants hiding in trees? 'Cause they are freaking good at it",
  "How did the blonde die raking leaves? She fell out of the tree.",
  "That guy is such a douche-bag! Is he single? Maybe I can fix him!",
  "My son just got a tattoo of a heart, a spade, a club, and a diamond, all without my permission. I gu...",
  "What do you call a potato in space? Spudnik",
  "How to get a cop's attention",
  "What happens to a necrophiliac after death? Reserection",
  "Why did the chicken hold a seance? To get to the other side.",
  "Where do baby cows go to eat lunch? At the calf-eteria.",
  "What's the difference between a painting and Jesus. You only require one nail to put up the painting...",
  "Mom:Do you want this?\n Me: No.\n Mom: Ok I'll give it to your brother.\n Me: No I want it.",
  "How do you fit 4 gays on one barstool? Flip it over!",
  "I am looking forward to 6pm Thanksgiving Day when Walmart opens its doors for its annual sale of tra...",
   "Sorry, but breaking up with you on facebook was the best way of letting all your friends know I'm av...",
   "I don't understand women. I also don't understand how a car works but I still drive it.",
   "How do they calculate global warming? Al-gore-ythms",
   "What do you call a Jedi who worries about not making deadlines? Panickin' Skywalker",
   "I invented a new word: Plagiarism!",
   "What's the best thing about Switzerland? I don't know, but their flag is a huge plus",
   "Why aren't koalas actual bears? They don't meet the koalafications.",
   "What's E.T. short for? Because he's only got little legs.",
   "Never criticize someone until you have walked a mile in their shoes. That way, when you criticize them, you'll be a mile away, and you'll have their shoes.",
   "What do Alexander the Great and Winnie the Pooh have in common? Same middle name.",
   "What's the difference between a hippo and a zippo? One is really heavy, and the other is a little lighter.",
   "What did the mayonnaise say when the refrigerator door was opened? Close the door, I'm dressing.",
   "I used to be addicted to soap. But I'm clean now.",
   "What did the left eye say to the right eye? Between you and me, something smells",
   "Why is England the wettest country? Because the queen has reigned there for years.",
   "It's hard to explain puns to kleptomaniacs. They always take things so literally.",
   "What's a foot long and slippery? A slipper."
]

module.exports=data